### ISSUE TITLE
Only works using 'multireducer' as key?

### ISSUE THREAD

**Issue by adailey14** [erikras/multireducer#73]
I am trying to use this for a project, and notice that it doesn't seem to work unless I use the key 'multireducer' in my top level 'combineReducers' reducer.

So this works:
```
export default combineReducers({
  multireducer: multireducer({
    list1: list,
    list2: list
  }),
});
```

But this doesn't work:

```
export default combineReducers({
  myLists: multireducer({
    list1: list,
    list2: list
  }),
});
```

It seems like 'multireducer' is hardcoded in connectMultireducer.js line 32:

    const slice = state.multireducer[multireducerKey];

Let me know if I'm misunderstanding something. But the above behavior seems to violate the way you say to use multireducer in the readme, and seems to limit you to only using one multireducer per project. Not sure the best way to solve this, maybe just change the behavior of multireducerConnect to be the same as react's connect, passing in the full state to the first argument rather than a slice of state?

**Comment by erikras** [comment]
Why yes, that does seem to be the case, for the reason you gave.

You cannot pass "the full state to the first argument rather than a slice of state" because `multireducer` needs to do some further slicing for you. If you _really_ needed some nesting, you'd have to pass in an additional key, but I think it probably works fine the way it is, simply changing the misleading docs.

**Comment by adailey14** [comment]
Very good thanks!
